### ISSUE TITLE
Refactoring the Readme.md 

### ISSUE THREAD

**Issue by rajneesh44** [maaz-bin-asad/Covid_19_Classifier#2]
@maaz-bin-asad, you can do a better practice that is, whatever you do, make a virtual environment and in it when the project is complete just run ```pip freeze>  requirements.txt```.
This will generate a requirements.txt file which contains all the libraries used in your project and installed in your virtual env.
This is better because the user will now will have to enter ```pip install requirements.txt``` and all libraries will be installed.

**Comment by maaz-bin-asad** [comment]
Okay
